version: "3"
services:

  test_kafka_consumer:
    image: 'test_kafka_consumer:staging'
    restart: always
    environment:
      - KAFKA_BROKER_ID=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
   
  test_kafka_producer:
    image: 'test_kafka_producer:staging'
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  zookeeper:
    restart: always
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    restart: always
    image: 'bitnami/kafka:latest'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
